services:
  # Наш API сервер
  api-server:
    build: ./back-end
    container_name: softy-pinko-back-end-task4

  # Наш веб-сервер Nginx
  front-server:
    build: ./front-end
    container_name: softy-pinko-front-end-task4
    ports:
      - "9000:9000"
    depends_on:
      - api-server
