services:
  # Сервис бэкенда (Flask API)
  api-server:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task4
    # Порт бэкенда не пробрасываем на хост, так как доступ нужен только фронтенду внутри сети

  # Сервис фронтенда (Nginx)
  front-server:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task4
    ports:
      - "9000:9000" # Маппинг HOST:CONTAINER
    depends_on:
      - api-server # Ждем запуска бэкенда перед стартом фронтенда
