services:
  back-end:
    build: ./back-end
    # Запускаем сразу 2 копии бэкенда
    deploy:
      replicas: 2
    image: softy-pinko-back-end:task6

  front-end:
    build: ./front-end
    image: softy-pinko-front-end:task6
    ports:
      - "80:80"
    depends_on:
      - back-end
